# Generated by Django 4.1.2 on 2022-10-31 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='id',
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.marca'),
        ),
    ]
