# Generated by Django 4.1.2 on 2022-11-08 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_marca_id_alter_marca_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('unidades', models.IntegerField(default=1)),
                ('importe', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('modelo', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('unidades', models.IntegerField(default=1)),
                ('precio', models.FloatField(default=0)),
                ('detalles', models.TextField(blank=True, max_length=255)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.marca')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='compras',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto'),
        ),
    ]
