# Generated by Django 4.1.2 on 2022-11-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_compras_producto_delete_product_compras_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compras',
            new_name='Compra',
        ),
    ]
